trigger:
 - master

pool:
   vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: dotnetappserviceconn2
    repository: 'dotnet-app-ci-cd'
    command: buildAndPush
    tags: |
     $(Build.BuildId)
     latest