trigger:
 - main

pool:
   vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: buildAndPush
  inputs:
    containerRegistry: dotnetserviceconn
    repository: 'dotnet-app-ci-cd'
    tags: |
     $(Build.BuildId)
     latest